library(veritable.r)
Sys.setenv(SWEAVE_STYLEPATH_DEFAULT=TRUE)
options(veritable.username = "fastmax", veritable.server = "dev.naviasystems.com")
#options(veritable.username = "fastmax2", veritable.server = "dev.naviasystems.com")
#options(veritable.username = "veritable", veritable.server = "127.0.0.1")
setwd("~/")